/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HelloStencil {
    }
    interface SvgRender {
        "height": number;
        "src": string;
        "width": number;
    }
}
declare global {
    interface HTMLHelloStencilElement extends Components.HelloStencil, HTMLStencilElement {
    }
    var HTMLHelloStencilElement: {
        prototype: HTMLHelloStencilElement;
        new (): HTMLHelloStencilElement;
    };
    interface HTMLSvgRenderElement extends Components.SvgRender, HTMLStencilElement {
    }
    var HTMLSvgRenderElement: {
        prototype: HTMLSvgRenderElement;
        new (): HTMLSvgRenderElement;
    };
    interface HTMLElementTagNameMap {
        "hello-stencil": HTMLHelloStencilElement;
        "svg-render": HTMLSvgRenderElement;
    }
}
declare namespace LocalJSX {
    interface HelloStencil {
    }
    interface SvgRender {
        "height"?: number;
        "src"?: string;
        "width"?: number;
    }
    interface IntrinsicElements {
        "hello-stencil": HelloStencil;
        "svg-render": SvgRender;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hello-stencil": LocalJSX.HelloStencil & JSXBase.HTMLAttributes<HTMLHelloStencilElement>;
            "svg-render": LocalJSX.SvgRender & JSXBase.HTMLAttributes<HTMLSvgRenderElement>;
        }
    }
}
